# Run full pipeline
default:
    uv run python source_download.py canada-mrdem
    uv run python source_download.py canada-hrdem

    # uv run python source_set_crs.py atsalzburg EPSG:31258

    uv run python source_set_nodata.py canada-mrdem -32767
    uv run python source_set_nodata.py canada-hrdem -32767

    # uv run python source_fix_orientation.py deberlin

    uv run python source_bounds.py canada-mrdem
    uv run python source_bounds.py canada-hrdem

    # uv run python source_polygonize.py frrgealti5stpm 32
    # uv run python source_polygonize.py frrgealti5mayotte 32

    #uv run python source_create_tarball.py canada-hrdem
    #uv run python source_create_tarball.py canada-mrdem

    uv run python aggregation_covering.py
    uv run python downsampling_covering.py
 
    uv run python aggregation_run.py
    uv run python downsampling_run.py
    uv run python remove_dangling_pmtiles.py
    uv run python create_index.py

    TMPDIR=/tmp uv run python bundle.py
    uv run python download_urls.py 0.0.0
    uv run python attribution.py
    # java -cp planetiler.jar Coverage.java # cf https://github.com/onthegomap/planetiler-examples

# Run debug pipeline
debug:
    uv run python source_download.py debug-glo30
    uv run python source_download.py debug-swissalti3d
    
    uv run python source_bounds.py debug-glo30
    uv run python source_bounds.py debug-swissalti3d
    
    uv run python aggregation_covering.py
    uv run python downsampling_covering.py
    
    uv run python aggregation_run.py
    uv run python downsampling_run.py

    uv run python remove_dangling_pmtiles.py
    TMPDIR=/tmp uv run python bundle.py 0.0.0
    uv run python download_urls.py 0.0.0
    uv run python attribution.py

# Upload to object storage. 
upload:
    uv run python upload.py
